2.0 ts
vorpaljs-reforged/vorpal pull request #1
Opened 2019-02-23 14:15 UTC by slinkardbrandon

2019-02-23 15:27 UTC, AdrieanKhisbe requested changes
We need **semi-columns**.
Besides the original code had them.

(But maybe that can wait prettier to be fixed)

2019-02-23 16:12 UTC, slinkardbrandon commented
In PR #2 with the prettier rules we can set  semicolons to true

2019-02-25 13:27 UTC, hongaar commented
> We need **semi-columns**.

Who needs semi-columns? 😉

2019-02-25 13:30 UTC, hongaar commented
Do we want to merge this to `develop` instead? Or maybe create a `next` branch so we keep the 'default' branches (develop/master) in sync with upstream? I'd say let's merge this as a start, and then start working our way through the code / fix ts warnings and errors next.

2019-02-25 13:30 UTC, hongaar approved these changes

2019-02-25 15:01 UTC, Ore4444 commented
@hongaar I think we can use "2.0-ts" as our "develop" branch.
@dthree will merge "2.0-ts" into "master" when we're done.
So for now we can branch out of and open PRs to "2.0-ts".
WDYT?

2019-02-25 17:10 UTC, slinkardbrandon commented
We were originally talking about following some resemblance of git flow here and utilizing develop / master and dropping the `2.0-ts` branch from our org (as it will all be TypeScript soon enough). I think in the end we'll create a PR from our org's master to the original vorpal's `2.0-ts` branch. 

It doesn't matter all that much which branch we use but I think @AdrieanKhisbe already set up develop as the default branch

2019-02-25 21:49 UTC, AdrieanKhisbe commented
@vorpaljs-reforged/vorpaldevelopers I think it's better we iterate on a `develop` branch, rather to wait for a long time to have `2.0-ts` land. 

(I intend to make some README modifications to make it clear about the vocation of this fork, and make it point on its CI)

2019-02-26 10:59 UTC, slinkardbrandon commented
Semi-colons aside (as we can bikeshed about that later), am I good to merge this one?

2019-02-26 11:15 UTC, Ore4444 commented
I agree about master/develop.
Can merge this PR.
Personally, I'm not using semicolons when I write code, but I use prettier to add them later.

2019-03-01 13:20 UTC, AdrieanKhisbe requested changes
I went over the modifications. To me
This could work as a base for migration.
Though we need to set up lint, and really refactor it. 

However I'll say we should take care of the two comment

2019-03-01 13:20 UTC, AdrieanKhisbe commented on package.json
> +    "gulp-typescript": "^5.0.0-alpha.3",
why picking the alpha?

2019-03-01 13:20 UTC, AdrieanKhisbe commented on package.json
> +    "@types/lodash": "^4.14.117",
@types should be in devDependecies if I'm not mistaken

2019-03-02 01:25 UTC, hongaar commented
I'm going to merge it now so we keep some momentum. Will fix the issues @AdrieanKhisbe brought up in a separate PR.

2019-03-02 01:26 UTC, merged